server.port=8082
spring.application.name=machine_management_ms
spring.datasource.url=jdbc:h2:mem:machines_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.poolName=HikariPool
spring.datasource.hikari.autoCommit=false
spring.datasource.hikari.leakDetectionThreshold=60000
spring.datasource.hikari.connectionTimeout=30000




